# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79623a8e6018f092cdbc643120925379268dc31b17e8f0ecbca4125d0ac2443d72e252749e2efa89ca8c0b1d4f0a7e9dfc2e5d27fad0f95f5752677ac6872d2b

test:
  secret_key_base: 911b3e34e0eca01214d4945aa25f28db1360cace5e46be3344e64e5d0b12bf85603d991ffdce99b965cc2a6e5681f633d8752e2526aa5887c7e6f988fae3185f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
